{
 "title": "Cadvisor metrics",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datacenter", "label": "datacenter", "query": "IAD*" },
   {
    "name": "environment",
    "query": "label_values(cadvisor_version_info, env)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cadvisor_version_info, job)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(cadvisor_version_info{env=~\"$environment\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$node\"}[5m])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$node\"}[5m  ])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{id=~\"/docker/.*\",instance=~\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Used Disk Space /",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\",instance=~\"$node\"} - node_filesystem_free_bytes{fstype=\"ext4\",instance=~\"$node\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "Available memory"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "Free memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}-(node_memory_Buffers_bytes{instance=~\"$node\"}+node_memory_Cached_bytes{instance=~\"$node\"}+node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "Used memory"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\",instance=~\"$node\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\",instance=~\"$node\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$node\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available Memory per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name!=\"\",instance=~\"$node\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$node\"}-container_memory_usage_bytes{name!=\"\",instance=~\"$node\"})by (name)"
    },
    {
     "expr": "max(container_memory_max_usage_bytes{name!=\"\",instance=~\"$node\"}) by (name)"
    }
   ]
  }
 ]
}